# Generated by Django 5.1.5 on 2025-01-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_address',
            field=models.CharField(max_length=42),
        ),
    ]
